GoogleCloudPlatform/getting-started-php

- bookshelf/test/unit/DatastoreModelTest.php
- testing/run_test_suite.sh
> Use SetUp instead of SetUpBeforeClass for code coverage.

- 2-structured-data/composer.json
- 2-structured-data/composer.lock
- 3-cloud-storage/composer.json
- 3-cloud-storage/composer.lock
- 4-auth/composer.json
- 4-auth/composer.lock
- 5-logging/composer.json
- 5-logging/composer.lock
- 6-compute-engine/composer.json
- 6-compute-engine/composer.lock
> publishing changes for #36

- _tuts/4-auth.diff
- _tuts/steps.json
Adds logged in test and testing webhooks
> adds logged in test

- _tuts/4-auth.diff
- _tuts/5-logging.diff
- _tuts/steps.json
> uses silex sessions when logged in

- testing/app-e2e.yaml
- testing/run_test_suite.sh
This shouldn't trigger e2e tests on travis unless explicitly set that envvar. I will configure jenkins jobs after merging this.
> Enables e2e test when RUN_E2E_TEST envvar is set.

- _tuts/2-structured-data.diff
- _tuts/steps.json
> Fixed Datastore listBooks for missing ids.

- _tuts/1-hello-world.diff
- _tuts/2-structured-data.diff
- _tuts/5-logging.diff
- _tuts/steps.json
I wanted to add PHP 5.6 explicitly. Also I did composer cleanups (alphabetical order).
> Added PHP 5.6, and composer clean-ups

- 1-hello-world/test/lib/GetConfigTrait.php
- 2-structured-data/config/settings.yml.dist
- 2-structured-data/test/lib/GetConfigTrait.php
- 3-cloud-storage/config/settings.yml.dist
- 3-cloud-storage/test/lib/GetConfigTrait.php
- 3-cloud-storage/test/unit/FileSystem/CloudStorageTest.php
- 3-cloud-storage/web/index.php
- 4-auth/config/settings.yml.dist
- 4-auth/test/lib/GetConfigTrait.php
- 4-auth/test/unit/FileSystem/CloudStorageTest.php
- 4-auth/web/index.php
- 5-logging/config/settings.yml.dist
- 5-logging/test/lib/GetConfigTrait.php
- 5-logging/test/unit/FileSystem/CloudStorageTest.php
- 5-logging/web/index.php
- 6-compute-engine/config/settings.yml.dist
- 6-compute-engine/test/lib/GetConfigTrait.php
- 6-compute-engine/test/unit/FileSystem/CloudStorageTest.php
- 6-compute-engine/web/index.php
Tests might fail, but let's see
> [PUBLISHED] 74 - Removed google_storage_bucket.

- .travis.yml
- testing/install_test_dependencies.sh
- testing/test_cleanup.sh
> Dynamically create a firewall rule for test.

- 2-structured-data/test/lib/DataModel/DataModelTestTrait.php
- 3-cloud-storage/test/lib/DataModel/DataModelTestTrait.php
- 4-auth/test/functional/ControllersTest.php
- 4-auth/test/lib/DataModel/DataModelTestTrait.php
- 5-logging/test/functional/ControllersTest.php
- 5-logging/test/lib/DataModel/DataModelTestTrait.php
- 6-compute-engine/test/functional/ControllersTest.php
- 6-compute-engine/test/lib/DataModel/DataModelTestTrait.php
> [PUBLISHED] 103 - Test improvements.

- _tuts/2-structured-data.diff
- _tuts/4-auth.diff
- _tuts/5-logging.diff
- _tuts/steps.json
> Test improvements.

- _tuts/2-structured-data.diff
- _tuts/steps.json
This is needed for running e2e test securely.
> Added an instance_tag.

- .travis.yml
> only install mongodb extension if we need to

- .travis.yml
> Retrying for installing test dependencies

- .travis.yml
- 1-hello-world/Dockerfile
- 1-hello-world/app.yaml
- 2-structured-data/Dockerfile
- 2-structured-data/app.yaml
- 3-cloud-storage/Dockerfile
- 3-cloud-storage/app.yaml
- 4-auth/Dockerfile
- 4-auth/app.yaml
- 5-logging/Dockerfile
- 5-logging/app.yaml
- _tuts/1-hello-world.diff
- _tuts/2-structured-data.diff
- _tuts/6-compute-engine.diff
- testing/install_test_dependencies.sh
@tmatsuo I am not sure why the differences between `BookshelfTest` and `E2eTest` are showing up here
> Change runtime to php

- 6-pubsub/test/app-e2e.yaml
- _tuts/6-pubsub.diff
- _tuts/optional-compute-engine.diff
- _tuts/optional-container-engine.diff
- optional-compute-engine/test/app-e2e.yaml
- optional-container-engine/test/app-e2e.yaml
> Added envvars for e2e tests.

- 6-pubsub/src/PubSub/Worker.php
- 6-pubsub/test/unit/PubSub/WorkerTest.php
- _tuts/6-pubsub.diff
- optional-compute-engine/src/PubSub/Worker.php
- optional-compute-engine/test/unit/PubSub/WorkerTest.php
- optional-container-engine/src/PubSub/Worker.php
- optional-container-engine/test/unit/PubSub/WorkerTest.php
> fix Worker calls to acknowledgeBatch

- 1-hello-world/app.yaml
- 2-structured-data/app.yaml
- 3-cloud-storage/app.yaml
- 4-auth/app.yaml
- 5-logging/app.yaml
- 6-pubsub/app.yaml
- _tuts/1-hello-world.diff
- _tuts/2-structured-data.diff
- _tuts/4-auth.diff
- _tuts/6-pubsub.diff
- _tuts/optional-kubernetes-engine.diff
like #168  but applied to all `app.yaml` files
> Updates app.yaml to keep costs low

- testing/install_test_dependencies.sh
See
https://github.com/GoogleCloudPlatform/getting-started-php/issues/180#issuecomment-360698613
> Stop deleting the firewall.

- .travis.yml
The tests are constantly failing. This is an attempt to use local mongodb server for the tests.
> Use local mongodb for the tests

- 2-structured-data/src/DataModel/MongoDb.php
- 3-cloud-storage/src/DataModel/MongoDb.php
- 4-auth/src/DataModel/MongoDb.php
- 5-logging/src/DataModel/MongoDb.php
- 6-pubsub/src/DataModel/MongoDb.php
- _tuts/2-structured-data.diff
- optional-compute-engine/src/DataModel/MongoDb.php
- optional-kubernetes-engine/src/DataModel/MongoDb.php
> Return string oid upon creating a book with the MongoDB backend

- optional-compute-engine/gce/deploy.sh
- optional-compute-engine/gce/startup-script.sh
> Fix bookshelf GCE tutorial

- 5-logging/src/app.php
> Fix deprecated flex Env Var

- .travis.yml
- gce/scripts/startup-script.sh
- gce/test/DeployTest.php
and fixes failing tests found as a result
> Ensures all tests execute, including deployment tests

- .kokoro/system_tests.sh
> chore: enable Build Cop Bot
